spring.application.name=examen

spring.datasource.url=jdbc:postgresql://localhost:5432/examen_vuelos
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true